export interface Feed {
    enabled: boolean | null,
    name: string,
    credits: string,
    interval: Date,
    lastChecked: Date,
    state: string,
    lastImportStart: Date,
    lastImportSuccess: Date,
    lastImportFailure: Date,
    lastCheckFailure: Date,
    downloadPending: boolean,
    agencies: number,
    routes: number,
    stopTimes: number,
    stops: number,
    trips: number,
    realTime: boolean,
}
